<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBH1qj6v\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBH1qj6v/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBH1qj6v.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBH1qj6v\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBH1qj6v\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BH1qj6v',
    'container.build_id' => '60cf9152',
    'container.build_time' => 1635858257,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBH1qj6v');
